services:
  db:
    image: postgres:16-alpine
    container_name: artisa-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: artisa_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - artisa_pg_data:/var/lib/postgresql/data

volumes:
  artisa_pg_data:
