# Generated by Django 6.1 on 2026-08-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
