# Generated by Django 6.1 on 2026-08-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_artwork_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='stock_status',
            field=models.CharField(blank=True, choices=[('in_stock', 'In Stock'), ('low_stock', 'Low Stock'), ('sold_out', 'Sold Out'), ('pre_order', 'Pre-order'), ('made_to_order', 'Made to Order'), ('reserved', 'Reserved'), ('coming_soon', 'Coming Soon')], default='in_stock', max_length=20, null=True),
        ),
    ]
