# Generated by Django 6.1 on 2026-08-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_artwork_stock_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='depth',
            field=models.FloatField(blank=True, help_text='Depth in cm (for 3D artworks)', null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='height',
            field=models.FloatField(blank=True, help_text='Height in cm', null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='width',
            field=models.FloatField(blank=True, help_text='Width in cm', null=True),
        ),
    ]
