# Generated by Django 6.1 on 2026-09-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0004_artwork_depth_artwork_height_artwork_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
