# Generated by Django 6.1 on 2026-09-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='commission_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='commission_categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='commission_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='commission_estimated_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='commission_starting_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='commission_will_do',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='commission_wont_do',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='specialties',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
