# Generated by Django 6.1 on 2026-09-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_artistprofile_commission_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistapplication',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='artistapplication',
            name='social_links',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='artistapplication',
            name='specialties',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
