# Generated by Django 6.1 on 2026-09-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_artist_application_extra_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='province',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
