# Generated by Django 6.1 on 2026-09-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='landmark',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='recipient_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
