# Generated by Django 6.1 on 2026-09-16 15:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_cancellation_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin_province', models.CharField(help_text='Artist province', max_length=100)),
                ('destination_province', models.CharField(help_text='Customer province', max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Shipping rates',
                'db_table': 'shipping_rates',
                'unique_together': {('origin_province', 'destination_province')},
            },
        ),
    ]
