# Generated by Django 6.1 on 2026-08-19 03:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(max_length=20)),
                ('target_ids', models.JSONField(default=list)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recommendation_cache',
                'unique_together': {('user', 'target_type')},
            },
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(max_length=20)),
                ('target_id', models.UUIDField()),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('favorite', 'Favorite'), ('cart_add', 'Cart Add'), ('purchase', 'Purchase'), ('commission', 'Commission'), ('profile_view', 'Profile View')], max_length=20)),
                ('weight', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_interactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='user_intera_user_id_862d52_idx'), models.Index(fields=['target_type', 'target_id'], name='user_intera_target__792512_idx'), models.Index(fields=['interaction_type'], name='user_intera_interac_516669_idx'), models.Index(fields=['created_at'], name='user_intera_created_712f51_idx')],
            },
        ),
    ]
